# Generated by Django 5.1.3 on 2025-10-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cancelled_at',
        ),
    ]
