# Generated by Django 5.1.3 on 2025-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='transaction',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='raw_response',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
