# Generated by Django 5.2.1 on 2026-01-17 13:49

import django.db.models.deletion
import django.utils.timezone
import hotels.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rename_validation_response_paymenttransaction_initiation_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='quote_id',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='board_type',
            field=models.CharField(default='Room Only', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_confirmed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_reference',
            field=models.CharField(db_index=True, default=hotels.models.generate_booking_reference, max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='business_address',
            field=models.TextField(default='Your Business Address'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='business_name',
            field=models.CharField(default='Your Travel Agency', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancellation_timeline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_out_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='confirmation_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='customer_service_email',
            field=models.EmailField(default='support@youragency.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='customer_service_phone',
            field=models.CharField(default='+880 1234 567890', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='due_at_accommodation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='guest_country_code',
            field=models.CharField(default='+880', max_length=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='guest_email',
            field=models.EmailField(default='guest@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='guest_name',
            field=models.CharField(default='Guest', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='guest_phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_address',
            field=models.TextField(default='Address not provided'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_country',
            field=models.CharField(default='Unknown Country', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_id',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(default='Unknown Hotel', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='rate_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='refundability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='terms_url',
            field=models.URLField(default='https://youragency.com/terms'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
