# Generated by Django 5.2.1 on 2026-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_hotelbooking_options_remove_hotelbooking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in_time',
            field=models.CharField(blank=True, default='2:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_out_time',
            field=models.CharField(blank=True, default='12:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='key_collection',
            field=models.TextField(blank=True, default='Standard check-in at hotel reception'),
        ),
    ]
