# Generated by Django 5.2.4 on 2025-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='destination_slug',
            field=models.SlugField(blank=True, editable=False, max_length=120),
        ),
    ]
