# Generated by Django 5.2.4 on 2025-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0002_holidaypackage_destination_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='duration',
            field=models.CharField(max_length=80),
        ),
    ]
