# Generated by Django 5.2.4 on 2025-07-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0003_alter_holidaypackage_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('processing_time', models.CharField(max_length=50)),
                ('validity', models.CharField(max_length=50)),
                ('entry_type', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='visa_types/')),
                ('requirements', models.JSONField(default=list)),
                ('policies', models.JSONField(default=list)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='holidays_visa.visacountry')),
            ],
        ),
    ]
