# Generated by Django 5.2.4 on 2025-07-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0004_visatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='documents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='visa_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='holidays_visa.visatype'),
        ),
    ]
