# Generated by Django 5.2.1 on 2025-08-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0005_visaapplication_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visacountry',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
