# Generated by Django 5.2.1 on 2025-08-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0006_visacountry_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visacountry',
            name='image',
        ),
    ]
