# Generated by Django 5.2.1 on 2025-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0009_umrahpackage_umrahbooking_umrahpackagedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
