# Generated by Django 5.2.1 on 2025-08-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0010_alter_visaapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahpackage',
            name='duration',
        ),
    ]
