# Generated by Django 5.2.5 on 2025-11-15 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holidays_visa", "0012_customholidayrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUmrahRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Umrah"),
                            ("premium", "Premium Umrah"),
                            ("deluxe", "Deluxe Umrah"),
                            ("family", "Family Package"),
                            ("group", "Group Package"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("duration", models.CharField(default="7", max_length=10)),
                ("number_of_pilgrims", models.PositiveIntegerField(default=1)),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("3-star", "3 Star Hotel"),
                            ("4-star", "4 Star Hotel"),
                            ("5-star", "5 Star Hotel"),
                            ("premium", "Premium Hotel"),
                            ("walking-distance", "Walking Distance to Haram"),
                        ],
                        default="3-star",
                        max_length=20,
                    ),
                ),
                ("special_requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_umrah_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
