# Generated by Django 5.2.1 on 2025-12-22 06:09

import datetime
from django.db import migrations, models

from decimal import Decimal
class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0013_customumrahrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visacountry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='visacountry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='visacountry',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='visacountry',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='visacountry',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='visacountry',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='fee',
        ),
        migrations.AddField(
            model_name='visatype',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
      migrations.AddField(
    model_name='visatype',
    name='processing_fee',
    field=models.DecimalField(
        decimal_places=2,
        max_digits=10,
        default=Decimal('0.00'),
    ),
    preserve_default=False,
),

        migrations.AddField(
            model_name='visatype',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visatype',
            name='visa_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='visa_countries/'),
        ),
    ]
