# Generated by Django 5.2.1 on 2025-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0014_remove_visacountry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
