# Generated by Django 5.2.1 on 2025-12-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_visa', '0015_visaapplication_service_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='processing_fee',
        ),
    ]
