# Generated by Django 5.2.1 on 2025-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuffleMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage markup (e.g., 10.00 for 10%)', max_digits=5)),
            ],
            options={
                'db_table': 'duffel_markups',
            },
        ),
    ]
