# Generated by Django 5.2.5 on 2025-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightpaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpaymenttransaction',
            name='duffel_offer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightpaymenttransaction',
            name='redirect_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightpaymenttransaction',
            name='redirect_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightpaymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ssl_success', 'SSL Payment Success'), ('payment_success_offer_expired', 'Payment Success - Offer Expired'), ('payment_success_order_failed', 'Payment Success - Order Failed'), ('complete_success', 'Complete Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=30),
        ),
    ]
