# Generated by Django 5.2.1 on 2025-12-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuffleMarkup',
        ),
    ]
